name: oc_with_rf
channels:
  - conda-forge
  - defaults
dependencies:
  - astropy=5.1
  - astroquery=0.4.6
  - matplotlib=3.5.2
  - numpy=1.23.5
  - pandas=1.5.2
  - python=3.10.8
  - scikit-learn=1.1.3
  - scipy=1.9.3
  - seaborn=0.12.2
  